export const canonicalFeeMappings = [
  {
    "accountCode": "10012899",
    "identityNo": "8002160132088",
    "portfolioName": "Blackbeard, Ginette",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Blackbeard, G Mrs",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 190
  },
  {
    "accountCode": "10012899",
    "identityNo": "8002160132088",
    "portfolioName": "Blackbeard, Ginette",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Blackbeard, G Mrs",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10016497",
    "identityNo": "7403295134083",
    "portfolioName": "Chin, Ashley",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Chin, Ashley",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10016497",
    "identityNo": "7403295134083",
    "portfolioName": "Chin, Ashley",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Chin, Ashley",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10023274",
    "identityNo": "7112126465182",
    "portfolioName": "Conder, Andrew",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Conder, Andrew",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10023274",
    "identityNo": "7112126465182",
    "portfolioName": "Conder, Andrew",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Conder, Andrew",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10023274",
    "identityNo": "7112126465182",
    "portfolioName": "Conder, Andrew",
    "platform": "Credo",
    "investmentName": "Diversified Trading Fund B1",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Conder, Andrew",
    "sourceInvestment": "Diversified Trading Fund B1",
    "matchScore": 200
  },
  {
    "accountCode": "10023274",
    "identityNo": "7112126465182",
    "portfolioName": "Conder, Andrew",
    "platform": "Credo",
    "investmentName": "Xhaos Special Opportunities Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Conder, Andrew",
    "sourceInvestment": "Xhaos Special Opportunities Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10015189",
    "identityNo": "10015189",
    "portfolioName": "Diva Trust",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Diva Trust",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10015189",
    "identityNo": "10015189",
    "portfolioName": "Diva Trust",
    "platform": "Credo",
    "investmentName": "Harmony Capital Limited Special Situations Class",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Diva Trust",
    "sourceInvestment": "Harmony Capital Limited Special Situations Class",
    "matchScore": 200
  },
  {
    "accountCode": "10015189",
    "identityNo": "10015189",
    "portfolioName": "Diva Trust",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Diva Trust",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10015188",
    "identityNo": "5407090212087",
    "portfolioName": "Divaris, Belle Norma",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Divaris, BN Mrs",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 190
  },
  {
    "accountCode": "10015188",
    "identityNo": "5407090212087",
    "portfolioName": "Divaris, Belle Norma",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Divaris, BN Mrs",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "Volkswagen AG",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "Volkswagen AG",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "Fundsmith Equity Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "Fundsmith Equity Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "Scottish Mortgage Investment Trust",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "Scottish Mortgage Investment Trust",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "HG Capital Trust",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "HG Capital Trust",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "Invesco Solar ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "Invesco Solar ETF",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "iShares Global Tech ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "iShares Global Tech ETF",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "Jinkosolar Holding Co Ltd",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "Jinkosolar Holding Co Ltd",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "Kraneshares CSI China Internet ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "Kraneshares CSI China Internet ETF",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10006632",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher & Monique",
    "platform": "Credo",
    "investmentName": "Prescient China Balanced Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, C Mr & M Mrs",
    "sourceInvestment": "Prescient China Balanced Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10018459",
    "identityNo": "YA3997806",
    "portfolioName": "Gennari, Enrico",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Gennari, Enrico",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10018459",
    "identityNo": "YA3997806",
    "portfolioName": "Gennari, Enrico",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Gennari, Enrico",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10022560",
    "identityNo": "9902050064086",
    "portfolioName": "Hoar, Bianca",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Hoar, Bianca Leigh",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 190
  },
  {
    "accountCode": "10022560",
    "identityNo": "9902050064086",
    "portfolioName": "Hoar, Bianca",
    "platform": "Credo",
    "investmentName": "Blackrock ICS US Dollar Liquidity Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Hoar, Bianca Leigh",
    "sourceInvestment": "Blackrock ICS US Dollar Liquidity Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10022560",
    "identityNo": "9902050064086",
    "portfolioName": "Hoar, Bianca",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Hoar, Bianca Leigh",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10016626",
    "identityNo": "C17145460",
    "portfolioName": "Ikigai Trust",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Ikigai Trust",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10016626",
    "identityNo": "C17145460",
    "portfolioName": "Ikigai Trust",
    "platform": "Credo",
    "investmentName": "Blackrock ICS US Dollar Liquidity Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Ikigai Trust",
    "sourceInvestment": "Blackrock ICS US Dollar Liquidity Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10016626",
    "identityNo": "C17145460",
    "portfolioName": "Ikigai Trust",
    "platform": "Credo",
    "investmentName": "Global X Copper Miners ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Ikigai Trust",
    "sourceInvestment": "Global X Copper Miners ETF",
    "matchScore": 200
  },
  {
    "accountCode": "10016626",
    "identityNo": "C17145460",
    "portfolioName": "Ikigai Trust",
    "platform": "Credo",
    "investmentName": "Nomura Global High Conviction Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Ikigai Trust",
    "sourceInvestment": "Nomura Global High Conviction Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10016626",
    "identityNo": "C17145460",
    "portfolioName": "Ikigai Trust",
    "platform": "Credo",
    "investmentName": "Rubrics Enhanced Yield UCITS Fund",
    "rebateAnnualPercent": 0.25,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Ikigai Trust",
    "sourceInvestment": "Rubrics Enhanced Yield UCITS Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10016626",
    "identityNo": "C17145460",
    "portfolioName": "Ikigai Trust",
    "platform": "Credo",
    "investmentName": "Diversified Trading Fund B1",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Ikigai Trust",
    "sourceInvestment": "Diversified Trading Fund B1",
    "matchScore": 200
  },
  {
    "accountCode": "10016626",
    "identityNo": "C17145460",
    "portfolioName": "Ikigai Trust",
    "platform": "Credo",
    "investmentName": "Xhaos Special Opportunities Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Ikigai Trust",
    "sourceInvestment": "Xhaos Special Opportunities Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10016626",
    "identityNo": "C17145460",
    "portfolioName": "Ikigai Trust",
    "platform": "Credo",
    "investmentName": "Prescient China Balanced Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Ikigai Trust",
    "sourceInvestment": "Prescient China Balanced Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10016626",
    "identityNo": "C17145460",
    "portfolioName": "Ikigai Trust",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Ikigai Trust",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10016626",
    "identityNo": "C17145460",
    "portfolioName": "Ikigai Trust",
    "platform": "Credo",
    "investmentName": "iShares Bitcoin Trust ETF",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Ikigai Trust",
    "sourceInvestment": "iShares Bitcoin Trust ETF",
    "matchScore": 200
  },
  {
    "accountCode": "10019107",
    "identityNo": "158906",
    "portfolioName": "Irving Trust",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Irving Trust",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10019107",
    "identityNo": "158906",
    "portfolioName": "Irving Trust",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Irving Trust",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10019107",
    "identityNo": "158906",
    "portfolioName": "Irving Trust",
    "platform": "Credo",
    "investmentName": "Diversified Trading Fund B1",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Irving Trust",
    "sourceInvestment": "Diversified Trading Fund B1",
    "matchScore": 200
  },
  {
    "accountCode": "10024145",
    "identityNo": "9708125146083",
    "portfolioName": "Jackson, Matt",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Jackson, Matt",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10024145",
    "identityNo": "9708125146083",
    "portfolioName": "Jackson, Matt",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Jackson, Matt",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10018479",
    "identityNo": "5407180767180",
    "portfolioName": "Malby, Francoise",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Malby, Francoise",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10018479",
    "identityNo": "5407180767180",
    "portfolioName": "Malby, Francoise",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Malby, Francoise",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10017234",
    "identityNo": "6504225046080",
    "portfolioName": "Mandy, Sean Gary",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Mandy, Sean Gary",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10019456",
    "identityNo": "7803285054086",
    "portfolioName": "Manolas, Viron",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Manolas, Viron",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10019456",
    "identityNo": "7803285054086",
    "portfolioName": "Manolas, Viron",
    "platform": "Credo",
    "investmentName": "Apple Inc",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Manolas, Viron",
    "sourceInvestment": "Apple Inc",
    "matchScore": 200
  },
  {
    "accountCode": "10019456",
    "identityNo": "7803285054086",
    "portfolioName": "Manolas, Viron",
    "platform": "Credo",
    "investmentName": "Defiance Quantum ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Manolas, Viron",
    "sourceInvestment": "Defiance Quantum ETF",
    "matchScore": 200
  },
  {
    "accountCode": "10019456",
    "identityNo": "7803285054086",
    "portfolioName": "Manolas, Viron",
    "platform": "Credo",
    "investmentName": "Invesco Nasdaq 100 ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Manolas, Viron",
    "sourceInvestment": "Invesco Nasdaq 100 ETF",
    "matchScore": 200
  },
  {
    "accountCode": "10019456",
    "identityNo": "7803285054086",
    "portfolioName": "Manolas, Viron",
    "platform": "Credo",
    "investmentName": "RSA Government Bond",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Manolas, Viron",
    "sourceInvestment": "RSA Government Bond",
    "matchScore": 200
  },
  {
    "accountCode": "10019457",
    "identityNo": "7803285054086",
    "portfolioName": "Manolas, Viron",
    "platform": "Credo",
    "investmentName": "Harmony Gold Mining",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Manolas, Viron",
    "sourceInvestment": "Harmony Gold Mining Co LTD",
    "matchScore": 188
  },
  {
    "accountCode": "10006739",
    "identityNo": "6610245172085",
    "portfolioName": "Maxwell, Dave",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Maxwell, Dave",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10006739",
    "identityNo": "6610245172085",
    "portfolioName": "Maxwell, Dave",
    "platform": "Credo",
    "investmentName": "iShares Global 100 ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Maxwell, Dave",
    "sourceInvestment": "iShares Global 100 ETF",
    "matchScore": 200
  },
  {
    "accountCode": "10006739",
    "identityNo": "6610245172085",
    "portfolioName": "Maxwell, Dave",
    "platform": "Credo",
    "investmentName": "iShares Physical Gold ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Maxwell, Dave",
    "sourceInvestment": "iShares Physical Gold ETF",
    "matchScore": 200
  },
  {
    "accountCode": "10006739",
    "identityNo": "6610245172085",
    "portfolioName": "Maxwell, Dave",
    "platform": "Credo",
    "investmentName": "BBVA Global Markets",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Maxwell, Dave",
    "sourceInvestment": "BBVA Global Markets",
    "matchScore": 200
  },
  {
    "accountCode": "10024884",
    "identityNo": "09021951/1",
    "portfolioName": "McGuirk, Pamela",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "McGuirk, Pamela",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "10024884",
    "identityNo": "09021951/1",
    "portfolioName": "McGuirk, Pamela",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "McGuirk, Pamela",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Digihost Technology Inc",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Digihost Technology Inc",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "HG Capital Trust",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "HG Capital Trust",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Blackrock ICS US Dollar Liquidity Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Blackrock ICS US Dollar Liquidity Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Amplify Transformational Data Sharing ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Amplify Transformational Data Sharing ETF",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Global X Copper Miners ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Global X Copper Miners ETF",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Dodge & Cox Worldwide Funds",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Dodge & Cox Worldwide Funds",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Nomura Global High Conviction Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Nomura Global High Conviction Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Rubrics Enhanced Yield UCITS Fund",
    "rebateAnnualPercent": 0.25,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Rubrics Enhanced Yield UCITS Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Diversified Trading Fund B1",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Diversified Trading Fund B1",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "Xhaos Special Opportunities Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "Xhaos Special Opportunities Fund",
    "matchScore": 190
  },
  {
    "accountCode": "10015250",
    "identityNo": "C354KY7M7",
    "portfolioName": "Sommer, Anna-Maria",
    "platform": "Credo",
    "investmentName": "iShares Bitcoin Trust ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Sommer, AM Ms",
    "sourceInvestment": "iShares Bitcoin Trust ETF",
    "matchScore": 190
  },
  {
    "accountCode": "10014441",
    "identityNo": "5004210080187",
    "portfolioName": "Von Arnim, Hildegard",
    "platform": "Credo",
    "investmentName": "Credo Trading account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Von Arnim, Achim & Hildegard",
    "sourceInvestment": "Credo Trading Account",
    "matchScore": 165
  },
  {
    "accountCode": "10014441",
    "identityNo": "5004210080187",
    "portfolioName": "Von Arnim, Hildegard",
    "platform": "Credo",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Von Arnim, Achim & Hildegard",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 165
  },
  {
    "accountCode": "7034",
    "identityNo": "7207200339087",
    "portfolioName": "Abrahams, Denise",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Abrahams, Denise",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "4972",
    "identityNo": "2015/068524/07",
    "portfolioName": "Apex Holdings (Pty) Ltd",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Apex Holdings (Pty) Ltd",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5724",
    "identityNo": "2009/040089/23",
    "portfolioName": "Apex Images CC",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Apex Images CC",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5215",
    "identityNo": "2015/194079/07",
    "portfolioName": "Apex Shark Expeditions (Pty) Ltd",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Apex Shark Expeditions (Pty) Ltd",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5202",
    "identityNo": "1986/002665/07",
    "portfolioName": "Bambino International (Pty) Ltd",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Bambino International (Pty) Ltd",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5531",
    "identityNo": "5707030094085",
    "portfolioName": "Briggs, Carol-Anne",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Briggs, Carol-Anne",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5531",
    "identityNo": "5707030094085",
    "portfolioName": "Briggs, Carol-Anne",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund C",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Briggs, Carol-Anne",
    "sourceInvestment": "Gryphon Dividend Income Fund C",
    "matchScore": 200
  },
  {
    "accountCode": "5195",
    "identityNo": "7403295134083",
    "portfolioName": "Chin, Ashley",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Chin, Ashley",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5025",
    "identityNo": "6007020264189",
    "portfolioName": "De Mey, Armelle",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "De Mey, Armelle",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5218",
    "identityNo": "9606210194085",
    "portfolioName": "De Mey, Katinga",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "De Mey, Katinga",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5447",
    "identityNo": "6510245060084",
    "portfolioName": "Eskinazi, Richard David",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Eskinazi, Richard David",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "4858",
    "identityNo": "7901040119085",
    "portfolioName": "Fallows, Monique Louise",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Fallows, ML Mrs",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 190
  },
  {
    "accountCode": "7002",
    "identityNo": "7306135199085",
    "portfolioName": "Freed, Justin",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Freed, Justin",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "7001",
    "identityNo": "7711225229082",
    "portfolioName": "Freed, Wayne",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Freed, Wayne",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5521",
    "identityNo": "1981/004074/07",
    "portfolioName": "Globrand Investments (Pty) Ltd",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Globrand Investments (Pty) Ltd",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5276",
    "identityNo": "1995/005536/07",
    "portfolioName": "Grufin Properties (Pty) Ltd",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Grufin Properties (Pty) Ltd",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5293",
    "identityNo": "4610110111186",
    "portfolioName": "Gruzd, Marie",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Gruzd, Marie",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5264",
    "identityNo": "4201045091089",
    "portfolioName": "Gruzd, Wilfred",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Gruzd, Wilfred",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5369",
    "identityNo": "9902050064086",
    "portfolioName": "Hoar, Bianca Leigh",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Hoar, Bianca Leigh",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5006",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 190
  },
  {
    "accountCode": "5365",
    "identityNo": "9701160063081",
    "portfolioName": "Hoar, Tayla",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Hoar, Tayla Leigh",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 190
  },
  {
    "accountCode": "4816",
    "identityNo": "7101120072086",
    "portfolioName": "Keren, Sara",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Keren, S Ms",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 190
  },
  {
    "accountCode": "5682",
    "identityNo": "IT3055/2005",
    "portfolioName": "Keurboom Trust",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Keurboom Trust",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "7123",
    "identityNo": "6710305180083",
    "portfolioName": "Lancaster, Dean",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Lancaster, Dean",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5020",
    "identityNo": "5102090073080",
    "portfolioName": "McGuirk, Pamela",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "McGuirk, Pamela",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5503",
    "identityNo": "7808230246083",
    "portfolioName": "Robinson, Cheryl",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Robinson, Cheryl",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5166",
    "identityNo": "6012290039089",
    "portfolioName": "Snitcher, Lauren Renee",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Snitcher, LR Ms",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 190
  },
  {
    "accountCode": "5266",
    "identityNo": "2005/004874/07",
    "portfolioName": "Stingray Accessory Manufacturers (Pty) Ltd",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Stingray Accessory Manufacturers (Pty) Ltd",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "5557",
    "identityNo": "4401080053081",
    "portfolioName": "Van Niekerk, Ann",
    "platform": "Gryphon",
    "investmentName": "Gryphon Dividend Income Fund",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Van Niekerk, Ann",
    "sourceInvestment": "Gryphon Dividend Income Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0316.6598",
    "identityNo": "6007020264189",
    "portfolioName": "De Mey, Armelle",
    "platform": "Julius Baer",
    "investmentName": "Julius Baer Trading Account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Armelle",
    "sourceInvestment": "Julius Baer Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "0316.6598",
    "identityNo": "6007020264189",
    "portfolioName": "De Mey, Armelle",
    "platform": "Julius Baer",
    "investmentName": "Blackrock ICS US Dollar Liquidity Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Armelle",
    "sourceInvestment": "Blackrock ICS US Dollar Liquidity Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0316.6598",
    "identityNo": "6007020264189",
    "portfolioName": "De Mey, Armelle",
    "platform": "Julius Baer",
    "investmentName": "Rubrics Enhanced Yield UCITS Fund",
    "rebateAnnualPercent": 0.25,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Armelle",
    "sourceInvestment": "Rubrics Enhanced Yield UCITS Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0316.6598",
    "identityNo": "6007020264189",
    "portfolioName": "De Mey, Armelle",
    "platform": "Julius Baer",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Armelle",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0316.6598",
    "identityNo": "6007020264189",
    "portfolioName": "De Mey, Armelle",
    "platform": "Julius Baer",
    "investmentName": "Diversified Trading Fund B1",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Armelle",
    "sourceInvestment": "Diversified Trading Fund B1",
    "matchScore": 200
  },
  {
    "accountCode": "0316.6598",
    "identityNo": "6007020264189",
    "portfolioName": "De Mey, Armelle",
    "platform": "Julius Baer",
    "investmentName": "Xhaos Special Opportunities Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Armelle",
    "sourceInvestment": "Xhaos Special Opportunities Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0321.7188",
    "identityNo": "9606210194085",
    "portfolioName": "De Mey, Katinga",
    "platform": "Julius Baer",
    "investmentName": "Julius Baer Trading Account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Katinga",
    "sourceInvestment": "Julius Baer Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "0321.7188",
    "identityNo": "9606210194085",
    "portfolioName": "De Mey, Katinga",
    "platform": "Julius Baer",
    "investmentName": "Blackrock ICS US Dollar Liquidity Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Katinga",
    "sourceInvestment": "Blackrock ICS US Dollar Liquidity Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0321.7188",
    "identityNo": "9606210194085",
    "portfolioName": "De Mey, Katinga",
    "platform": "Julius Baer",
    "investmentName": "Rubrics Enhanced Yield UCITS Fund",
    "rebateAnnualPercent": 0.25,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Katinga",
    "sourceInvestment": "Rubrics Enhanced Yield UCITS Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0321.7188",
    "identityNo": "9606210194085",
    "portfolioName": "De Mey, Katinga",
    "platform": "Julius Baer",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Katinga",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0321.7188",
    "identityNo": "9606210194085",
    "portfolioName": "De Mey, Katinga",
    "platform": "Julius Baer",
    "investmentName": "Xhaos Special Opportunities Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Katinga",
    "sourceInvestment": "Xhaos Special Opportunities Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0315.2553",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Julius Baer",
    "investmentName": "Julius Baer Trading Account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Julius Baer Trading Account",
    "matchScore": 190
  },
  {
    "accountCode": "0315.2553",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Julius Baer",
    "investmentName": "Dodge & Cox Worldwide Funds",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Dodge & Cox Worldwide Funds",
    "matchScore": 190
  },
  {
    "accountCode": "0315.2553",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Julius Baer",
    "investmentName": "Global X Copper Miners ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Global X Copper Miners ETF",
    "matchScore": 190
  },
  {
    "accountCode": "0315.2553",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Julius Baer",
    "investmentName": "Invesco Global Clean Energy ETF",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Invesco Global Clean Energy ETF",
    "matchScore": 190
  },
  {
    "accountCode": "0315.2553",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Julius Baer",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 190
  },
  {
    "accountCode": "0315.2553",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Julius Baer",
    "investmentName": "Diversified Trading Fund B1",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Diversified Trading Fund B1",
    "matchScore": 190
  },
  {
    "accountCode": "0315.2553",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Julius Baer",
    "investmentName": "Xhaos Special Opportunities Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Xhaos Special Opportunities Fund",
    "matchScore": 190
  },
  {
    "accountCode": "0315.2553",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Julius Baer",
    "investmentName": "Gold",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Gold",
    "matchScore": 190
  },
  {
    "accountCode": "0315.2553",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Julius Baer",
    "investmentName": "Prescient China Balanced Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Prescient China Balanced Fund",
    "matchScore": 190
  },
  {
    "accountCode": "0316.9089",
    "identityNo": "548451598",
    "portfolioName": "Hughes, Carol",
    "platform": "Julius Baer",
    "investmentName": "Julius Baer Trading Account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hughes, Carol Violet",
    "sourceInvestment": "Julius Baer Trading Account",
    "matchScore": 190
  },
  {
    "accountCode": "0316.9089",
    "identityNo": "548451598",
    "portfolioName": "Hughes, Carol",
    "platform": "Julius Baer",
    "investmentName": "Wealthworks Global Flexible Fund (USD)",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hughes, Carol Violet",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 178
  },
  {
    "accountCode": "0315.4230",
    "identityNo": "6909305074086",
    "portfolioName": "Keren, Avi & Glynis",
    "platform": "Julius Baer",
    "investmentName": "Julius Baer Trading Account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Keren, Avi & Glynis",
    "sourceInvestment": "Julius Baer Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "0315.4230",
    "identityNo": "6909305074086",
    "portfolioName": "Keren, Avi & Glynis",
    "platform": "Julius Baer",
    "investmentName": "Gold",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Keren, Avi & Glynis",
    "sourceInvestment": "Gold",
    "matchScore": 200
  },
  {
    "accountCode": "0321.5916",
    "identityNo": "70414",
    "portfolioName": "Marula Trading & Investments Limited",
    "platform": "Julius Baer",
    "investmentName": "Julius Baer Trading Account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Marula Trading & Investments Limited",
    "sourceInvestment": "Julius Baer Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "0321.5916",
    "identityNo": "70414",
    "portfolioName": "Marula Trading & Investments Limited",
    "platform": "Julius Baer",
    "investmentName": "Blackrock ICS US Dollar Liquidity Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Marula Trading & Investments Limited",
    "sourceInvestment": "Blackrock ICS US Dollar Liquidity Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0321.5916",
    "identityNo": "70414",
    "portfolioName": "Marula Trading & Investments Limited",
    "platform": "Julius Baer",
    "investmentName": "Meituan",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Marula Trading & Investments Limited",
    "sourceInvestment": "Meituan",
    "matchScore": 200
  },
  {
    "accountCode": "0321.5916",
    "identityNo": "70414",
    "portfolioName": "Marula Trading & Investments Limited",
    "platform": "Julius Baer",
    "investmentName": "Tencent Holdings Limited",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Marula Trading & Investments Limited",
    "sourceInvestment": "Tencent Holdings Limited",
    "matchScore": 200
  },
  {
    "accountCode": "0321.5916",
    "identityNo": "70414",
    "portfolioName": "Marula Trading & Investments Limited",
    "platform": "Julius Baer",
    "investmentName": "Alibaba Group Holding",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Marula Trading & Investments Limited",
    "sourceInvestment": "Alibaba Group Holding",
    "matchScore": 200
  },
  {
    "accountCode": "0321.5916",
    "identityNo": "70414",
    "portfolioName": "Marula Trading & Investments Limited",
    "platform": "Julius Baer",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Marula Trading & Investments Limited",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0321.5916",
    "identityNo": "70414",
    "portfolioName": "Marula Trading & Investments Limited",
    "platform": "Julius Baer",
    "investmentName": "Diversified Trading Fund B1",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Marula Trading & Investments Limited",
    "sourceInvestment": "Diversified Trading Fund B1",
    "matchScore": 200
  },
  {
    "accountCode": "0321.5916",
    "identityNo": "70414",
    "portfolioName": "Marula Trading & Investments Limited",
    "platform": "Julius Baer",
    "investmentName": "Xhaos Special Opportunities Fund D",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Marula Trading & Investments Limited",
    "sourceInvestment": "Xhaos Special Opportunities Fund D",
    "matchScore": 200
  },
  {
    "accountCode": "0319.4475",
    "identityNo": "56121 C2/GBL",
    "portfolioName": "Terra-Mater Limited",
    "platform": "Julius Baer",
    "investmentName": "Julius Baer Trading Account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Terra-Mater Limited",
    "sourceInvestment": "Julius Baer Trading Account",
    "matchScore": 200
  },
  {
    "accountCode": "0319.4475",
    "identityNo": "56121 C2/GBL",
    "portfolioName": "Terra-Mater Limited",
    "platform": "Julius Baer",
    "investmentName": "Scottish Mortgage Investment Trust",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Terra-Mater Limited",
    "sourceInvestment": "Scottish Mortgage Investment Trust",
    "matchScore": 200
  },
  {
    "accountCode": "0319.4475",
    "identityNo": "56121 C2/GBL",
    "portfolioName": "Terra-Mater Limited",
    "platform": "Julius Baer",
    "investmentName": "Wealthworks Global Flexible Fund",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Terra-Mater Limited",
    "sourceInvestment": "Wealthworks Global Flexible Fund",
    "matchScore": 200
  },
  {
    "accountCode": "0319.4475",
    "identityNo": "56121 C2/GBL",
    "portfolioName": "Terra-Mater Limited",
    "platform": "Julius Baer",
    "investmentName": "Diversified Trading Fund B1",
    "rebateAnnualPercent": 0.5,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Terra-Mater Limited",
    "sourceInvestment": "Diversified Trading Fund B1",
    "matchScore": 200
  },
  {
    "accountCode": "0319.4475",
    "identityNo": "56121 C2/GBL",
    "portfolioName": "Terra-Mater Limited",
    "platform": "Julius Baer",
    "investmentName": "Xhaos Special Opportunities Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.7000000000000001,
    "sourceClient": "Terra-Mater Limited",
    "sourceInvestment": "Xhaos Special Opportunities Fund",
    "matchScore": 200
  },
  {
    "accountCode": "1003725",
    "identityNo": "7209215223082",
    "portfolioName": "Fallows, Christopher",
    "platform": "Northstar FNB",
    "investmentName": "FNB Securities Trading Account (Northstar)",
    "rebateAnnualPercent": 0.75,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Fallows, C Mr",
    "sourceInvestment": "FNB Securities (Northstar)",
    "matchScore": 160
  },
  {
    "accountCode": "197970",
    "identityNo": "7101120072086",
    "portfolioName": "Keren, Sara",
    "platform": "Peresec",
    "investmentName": "Peresec Trading Account",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Keren, S Ms",
    "sourceInvestment": "Peresec Trading Account",
    "matchScore": 190
  },
  {
    "accountCode": "LAU00746",
    "identityNo": "1927/000221/07",
    "portfolioName": "Commercial Buildings (Pty) Ltd",
    "platform": "Prescient",
    "investmentName": "Laurium Stable Prescient Fund A2",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.79,
    "sourceClient": "Commercial Buildings (Pty) Ltd",
    "sourceInvestment": "Laurium Stable Prescient Fund A2",
    "matchScore": 200
  },
  {
    "accountCode": "PRI50594441",
    "identityNo": "2015/068524/07",
    "portfolioName": "Apex Holdings (Pty) Ltd",
    "platform": "Prime",
    "investmentName": "Centaur BCI Flexible Fund ( C )",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Apex Holdings (Pty) Ltd",
    "sourceInvestment": "Centaur Bci Flexible Fund ( C )",
    "matchScore": 200
  },
  {
    "accountCode": "PRI50594441",
    "identityNo": "2015/068524/07",
    "portfolioName": "Apex Holdings (Pty) Ltd",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Cautious Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Apex Holdings (Pty) Ltd",
    "sourceInvestment": "Wealthworks Prime Cautious Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI50594441",
    "identityNo": "2015/068524/07",
    "portfolioName": "Apex Holdings (Pty) Ltd",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Apex Holdings (Pty) Ltd",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202650602325",
    "identityNo": "2009/040089/23",
    "portfolioName": "Apex Images CC",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Apex Images CC",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202650602325",
    "identityNo": "2009/040089/23",
    "portfolioName": "Apex Images CC",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Cautious Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Apex Images CC",
    "sourceInvestment": "Wealthworks Prime Cautious Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202110280001",
    "identityNo": "8002160132088",
    "portfolioName": "Blackbeard, Ginette",
    "platform": "Prime",
    "investmentName": "Prescient Income Provider Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Blackbeard, G Mrs",
    "sourceInvestment": "Prescient Income Provider Fund",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202110280001",
    "identityNo": "8002160132088",
    "portfolioName": "Blackbeard, Ginette",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Blackbeard, G Mrs",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202110280001",
    "identityNo": "8002160132088",
    "portfolioName": "Blackbeard, Ginette",
    "platform": "Prime",
    "investmentName": "Cash",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Blackbeard, G Mrs",
    "sourceInvestment": "Cash",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202212210002",
    "identityNo": "1927/000221/07",
    "portfolioName": "Commercial Buildings (Pty) Ltd",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.79,
    "sourceClient": "Commercial Buildings (Pty) Ltd",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI201806040001",
    "identityNo": "6007020264189",
    "portfolioName": "De Mey, Armelle",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "De Mey, Armelle",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI201908270001",
    "identityNo": "9606210194085",
    "portfolioName": "De Mey, Katinga",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "De Mey, Katinga",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202212050001",
    "identityNo": "5708225780082",
    "portfolioName": "Eskinazi, Ray",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Eskinazi, Raymond Nessim",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 190
  },
  {
    "accountCode": "PRI201911150005",
    "identityNo": "6510245060084",
    "portfolioName": "Eskinazi, Richard David",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds (Preservation Pension Plan)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Eskinazi, Richard David",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 188
  },
  {
    "accountCode": "PRI201911150005",
    "identityNo": "6510245060084",
    "portfolioName": "Eskinazi, Richard David",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds (Retirement Plan)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Eskinazi, Richard David",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 188
  },
  {
    "accountCode": "PRI202012090001",
    "identityNo": "6510245060084",
    "portfolioName": "Eskinazi, Richard David",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds (Preservation Provident Plan)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Eskinazi, Richard David",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 188
  },
  {
    "accountCode": "PRI201803280003",
    "identityNo": "6510245060084",
    "portfolioName": "Eskinazi, Richard David",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Eskinazi, Richard David",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI201802210001",
    "identityNo": "6912015078082",
    "portfolioName": "Eskinazi, Roger Jeane-Pierre",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Eskinazi, Raymond Nessim",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202008120001",
    "identityNo": "7901040119085",
    "portfolioName": "Fallows, Monique Louise",
    "platform": "Prime",
    "investmentName": "36ONE Flexible",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, ML Mrs",
    "sourceInvestment": "36ONE Flexible",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202008120001",
    "identityNo": "7901040119085",
    "portfolioName": "Fallows, Monique Louise",
    "platform": "Prime",
    "investmentName": "Fairtree Equity Prescient Fund (A1)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, ML Mrs",
    "sourceInvestment": "Fairtree Equity Prescient Fund",
    "matchScore": 178
  },
  {
    "accountCode": "PRI202008120001",
    "identityNo": "7901040119085",
    "portfolioName": "Fallows, Monique Louise",
    "platform": "Prime",
    "investmentName": "Centaur BCI Flexible Fund ( C )",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, ML Mrs",
    "sourceInvestment": "Centaur Bci Flexible Fund ( C )",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202008120001",
    "identityNo": "7901040119085",
    "portfolioName": "Fallows, Monique Louise",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fallows, ML Mrs",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202110110005",
    "identityNo": "5202120048084",
    "portfolioName": "Fowler, Merle",
    "platform": "Prime",
    "investmentName": "Prescient Income Provider Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fowler, Merle",
    "sourceInvestment": "Prescient Income Provider Fund",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202110110005",
    "identityNo": "5202120048084",
    "portfolioName": "Fowler, Merle",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Cautious Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fowler, Merle",
    "sourceInvestment": "Wealthworks Prime Cautious Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202110110005",
    "identityNo": "5202120048084",
    "portfolioName": "Fowler, Merle",
    "platform": "Prime",
    "investmentName": "Cash",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Fowler, Merle",
    "sourceInvestment": "Cash",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202308310001",
    "identityNo": "IT000218/2022(C)",
    "portfolioName": "Gennari Family Trust",
    "platform": "Prime",
    "investmentName": "Prescient Income Provider Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Gennari Family Trust",
    "sourceInvestment": "Prescient Income Provider Fund",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202308310001",
    "identityNo": "IT000218/2022(C)",
    "portfolioName": "Gennari Family Trust",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Cautious Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Gennari Family Trust",
    "sourceInvestment": "Wealthworks Prime Cautious Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202308310001",
    "identityNo": "IT000218/2022(C)",
    "portfolioName": "Gennari Family Trust",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Gennari Family Trust",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202308310001",
    "identityNo": "IT000218/2022(C)",
    "portfolioName": "Gennari Family Trust",
    "platform": "Prime",
    "investmentName": "Cash",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Gennari Family Trust",
    "sourceInvestment": "Cash",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202450599542",
    "identityNo": "8405255864186",
    "portfolioName": "Hedley, James",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Hedley, James",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI201802280001",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds (Retirement Plan)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 178
  },
  {
    "accountCode": "PRI201807090001",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds (Investment Plan)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 178
  },
  {
    "accountCode": "PRI202108240002",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "Fairtree Equity Prescient (A1)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Fairtree Equity Prescient (A1)",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202108240002",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "ClucasGray Prescient Equity Fund (B1)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "ClucasGray Prescient Equity Fund (B1)",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202108240002",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "Laurium Flexible Prescient Fund Fund (B4)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Laurium Flexible Prescient Fund Fund (B4)",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202108240002",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Cautious Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Wealthworks Prime Cautious Fund of Funds",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202108240002",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "36One Bci Flexible Opportunity Fund (A)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "36One Bci Flexible Opportunity Fund (A)",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202108240002",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "Centaur Bci Flexible Fund (C)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Centaur Bci Flexible Fund (C)",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202108240002",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "Obsidian SCI Equity Fund (B3)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Obsidian SCI Equity Fund (B3)",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202108240002",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "Coronation Global Emerging Markets Flexible (P)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Coronation Global Emerging Markets Flexible (P)",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202108240002",
    "identityNo": "6801105008085",
    "portfolioName": "Hoar, Marc",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds (Investment Plan)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Hoar, M Mr",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 178
  },
  {
    "accountCode": "PRI202450595140",
    "identityNo": "2002/006975/07",
    "portfolioName": "Kovacs Investments 492 (PTY) LTD",
    "platform": "Prime",
    "investmentName": "Prescient Income Provider (A2)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Kovacs Investments 492 (Pty) Ltd",
    "sourceInvestment": "Prescient Income Provider (A2)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202450595140",
    "identityNo": "2002/006975/07",
    "portfolioName": "Kovacs Investments 492 (PTY) LTD",
    "platform": "Prime",
    "investmentName": "Laurium Stable Prescient Fund (A2)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Kovacs Investments 492 (Pty) Ltd",
    "sourceInvestment": "Laurium Stable Prescient Fund (A2)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202450595140",
    "identityNo": "2002/006975/07",
    "portfolioName": "Kovacs Investments 492 (PTY) LTD",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Cautious FOF (B)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Kovacs Investments 492 (Pty) Ltd",
    "sourceInvestment": "Wealthworks Prime Cautious FOF (B)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202202070007",
    "identityNo": "6701275028089",
    "portfolioName": "Mackay Davidson, Charles Stuart",
    "platform": "Prime",
    "investmentName": "Prescient Income Provider Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Mackay Davidson, Charles Stuart",
    "sourceInvestment": "Prescient Income Provider Fund",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202202070007",
    "identityNo": "6701275028089",
    "portfolioName": "Mackay Davidson, Charles Stuart",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Mackay Davidson, Charles Stuart",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202202070007",
    "identityNo": "6701275028089",
    "portfolioName": "Mackay Davidson, Charles Stuart",
    "platform": "Prime",
    "investmentName": "Cash",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Mackay Davidson, Charles Stuart",
    "sourceInvestment": "Cash",
    "matchScore": 200
  },
  {
    "accountCode": "PRI201911110003",
    "identityNo": "6211080127084",
    "portfolioName": "Mandy, Shelley Anne",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Mandy, Shelley Anne",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI201911110003",
    "identityNo": "6211080127084",
    "portfolioName": "Mandy, Shelley Anne",
    "platform": "Prime",
    "investmentName": "Cash",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Mandy, Shelley Anne",
    "sourceInvestment": "Cash",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202550601174",
    "identityNo": "FN497554",
    "portfolioName": "Moyo, Thithibele",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Moyo, Thithibele",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202103150001",
    "identityNo": "7808230246083",
    "portfolioName": "Robinson, Cheryl",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Robinson, Cheryl",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202209280001",
    "identityNo": "5306120097080",
    "portfolioName": "Smuts, Hanny",
    "platform": "Prime",
    "investmentName": "Matrix SCI Stable Income Fund B1",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Smuts, Hanny",
    "sourceInvestment": "Matrix SCI Stable Income Fund B1",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202209280001",
    "identityNo": "5306120097080",
    "portfolioName": "Smuts, Hanny",
    "platform": "Prime",
    "investmentName": "Prescient Income Provider Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Smuts, Hanny",
    "sourceInvestment": "Prescient Income Provider Fund",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202209280001",
    "identityNo": "5306120097080",
    "portfolioName": "Smuts, Hanny",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Cautious Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Smuts, Hanny",
    "sourceInvestment": "Wealthworks Prime Cautious Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202209280001",
    "identityNo": "5306120097080",
    "portfolioName": "Smuts, Hanny",
    "platform": "Prime",
    "investmentName": "Cash",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Smuts, Hanny",
    "sourceInvestment": "Cash",
    "matchScore": 200
  },
  {
    "accountCode": "PRI201903150001",
    "identityNo": "6012290039089",
    "portfolioName": "Snitcher, Lauren Renee",
    "platform": "Prime",
    "investmentName": "Prescient Income Provider Fund",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5499999999999999,
    "sourceClient": "Snitcher, LR Ms",
    "sourceInvestment": "Prescient Income Provider Fund",
    "matchScore": 190
  },
  {
    "accountCode": "PRI201903150001",
    "identityNo": "6012290039089",
    "portfolioName": "Snitcher, Lauren Renee",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.5499999999999999,
    "sourceClient": "Snitcher, LR Ms",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 190
  },
  {
    "accountCode": "PRI201903150001",
    "identityNo": "6012290039089",
    "portfolioName": "Snitcher, Lauren Renee",
    "platform": "Prime",
    "investmentName": "Cash",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5499999999999999,
    "sourceClient": "Snitcher, LR Ms",
    "sourceInvestment": "Cash",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202204040004",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 (Pty) Ltd",
    "platform": "Prime",
    "investmentName": "36One BCI Global Equity Feeder Fund (A) (36FNDA)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd",
    "sourceInvestment": "36One BCI Global Equity Feeder Fund (A) (36FNDA)",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202204040004",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 (Pty) Ltd",
    "platform": "Prime",
    "investmentName": "Catalyst SCI Global Real Estate SCI Feeder (B) (CGRE)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd",
    "sourceInvestment": "Catalyst SCI Global Real Estate SCI Feeder (B) (CGRE)",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202204040004",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 (Pty) Ltd",
    "platform": "Prime",
    "investmentName": "Centaur Bci Flexible Fund ( C )",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd",
    "sourceInvestment": "Centaur Bci Flexible Fund ( C )",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202204040004",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 (Pty) Ltd",
    "platform": "Prime",
    "investmentName": "ClucasGray Prescient Equity Fund (B1) (CGPB1)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd",
    "sourceInvestment": "ClucasGray Prescient Equity Fund (B1) (CGPB1)",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202204040004",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 (Pty) Ltd",
    "platform": "Prime",
    "investmentName": "Coronation Global Emerging Markets Flexible [ZAR] Fund (P) (CGEMB4)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd",
    "sourceInvestment": "Coronation Global Emerging Markets Flexible [ZAR] Fund (P) (CGEMB4)",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202204040004",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 (Pty) Ltd",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202450595273",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 Acc 2",
    "platform": "Prime",
    "investmentName": "Laurium Stable Prescient Fund (A2)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd Acc 2",
    "sourceInvestment": "Laurium Stable Prescient Fund (A2)",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202450595273",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 Acc 2",
    "platform": "Prime",
    "investmentName": "Obsidian SCI Balanced Fund (B1)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd Acc 2",
    "sourceInvestment": "Obsidian SCI Balanced Fund (B1)",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202450595273",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 Acc 2",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed FOF (A)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd Acc 2",
    "sourceInvestment": "Wealthworks Prime Managed FOF (A)",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202450595273",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 Acc 2",
    "platform": "Prime",
    "investmentName": "Centaur Bci Flexible Fund (C)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd",
    "sourceInvestment": "Centaur Bci Flexible Fund ( C )",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202450595273",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 Acc 2",
    "platform": "Prime",
    "investmentName": "36One Bci Flexible Opportunity Fund (A)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd Acc 2",
    "sourceInvestment": "36One Bci Flexible Opportunity Fund (A)",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202450595273",
    "identityNo": "2008/025068/07",
    "portfolioName": "Sweet Grass Trading 12 Acc 2",
    "platform": "Prime",
    "investmentName": "Fairtree Equity Prescient (A1)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.65,
    "sourceClient": "Sweet Grass Trading (Pty) Ltd Acc 2",
    "sourceInvestment": "Fairtree Equity Prescient (A1)",
    "matchScore": 165
  },
  {
    "accountCode": "PRI202650602593",
    "identityNo": "8908115051084",
    "portfolioName": "Thomas, Mayne",
    "platform": "Prime",
    "investmentName": "Coronation Global Emerging Markets Flexible (P)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Thomas, Mayne",
    "sourceInvestment": "Coronation Global Emerging Markets Flexible (P)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202650602593",
    "identityNo": "8908115051084",
    "portfolioName": "Thomas, Mayne",
    "platform": "Prime",
    "investmentName": "Centaur Bci Flexible Fund (C)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Thomas, Mayne",
    "sourceInvestment": "Centaur Bci Flexible Fund (C)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202650602593",
    "identityNo": "8908115051084",
    "portfolioName": "Thomas, Mayne",
    "platform": "Prime",
    "investmentName": "Laurium Flexible Prescient Fund Fund (B4)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Thomas, Mayne",
    "sourceInvestment": "Laurium Flexible Prescient Fund Fund (B4)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202650602593",
    "identityNo": "8908115051084",
    "portfolioName": "Thomas, Mayne",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Cautious FOF (A)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Thomas, Mayne",
    "sourceInvestment": "Wealthworks Prime Cautious FOF (A)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202650602593",
    "identityNo": "8908115051084",
    "portfolioName": "Thomas, Mayne",
    "platform": "Prime",
    "investmentName": "36One Bci Flexible Opportunity Fund (A)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Thomas, Mayne",
    "sourceInvestment": "36One Bci Flexible Opportunity Fund (A)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202650602593",
    "identityNo": "8908115051084",
    "portfolioName": "Thomas, Mayne",
    "platform": "Prime",
    "investmentName": "Fairtree Equity Prescient (A1)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Thomas, Mayne",
    "sourceInvestment": "Fairtree Equity Prescient (A1)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202650602593",
    "identityNo": "8908115051084",
    "portfolioName": "Thomas, Mayne",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed FOF (A)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Thomas, Mayne",
    "sourceInvestment": "Wealthworks Prime Managed FOF (A)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202110190002",
    "identityNo": "IT4597/98",
    "portfolioName": "Three Sisters Trust",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Three Sisters Trust",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202111020001",
    "identityNo": "4401080053081",
    "portfolioName": "Van Niekerk, Ann",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Cautious Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Van Niekerk, Ann",
    "sourceInvestment": "Wealthworks Prime Cautious Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202111020001",
    "identityNo": "4401080053081",
    "portfolioName": "Van Niekerk, Ann",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Van Niekerk, Ann",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202111020001",
    "identityNo": "4401080053081",
    "portfolioName": "Van Niekerk, Ann",
    "platform": "Prime",
    "investmentName": "Cash",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Van Niekerk, Ann",
    "sourceInvestment": "Cash",
    "matchScore": 200
  },
  {
    "accountCode": "PRI201811080002",
    "identityNo": "4507195061080",
    "portfolioName": "Von Arnim, Achim Alard Giselher",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Von Arnim, AAG Mr",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 190
  },
  {
    "accountCode": "PRI201811080002",
    "identityNo": "4507195061080",
    "portfolioName": "Von Arnim, Achim Alard Giselher",
    "platform": "Prime",
    "investmentName": "Cash",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Von Arnim, AAG Mr",
    "sourceInvestment": "Cash",
    "matchScore": 190
  },
  {
    "accountCode": "PRI201811080003",
    "identityNo": "5004210080187",
    "portfolioName": "Von Arnim, Helga Hildegard Katharina",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Von Arnim, HHK Mrs",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 190
  },
  {
    "accountCode": "PRI201811080003",
    "identityNo": "5004210080187",
    "portfolioName": "Von Arnim, Helga Hildegard Katharina",
    "platform": "Prime",
    "investmentName": "Cash",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.75,
    "sourceClient": "Von Arnim, HHK Mrs",
    "sourceInvestment": "Cash",
    "matchScore": 190
  },
  {
    "accountCode": "PRI202450595137",
    "identityNo": "0406055186083",
    "portfolioName": "Wilmans, Joshua",
    "platform": "Prime",
    "investmentName": "Coronation Global Emerging Markets Flexible (P)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Wilmans, Joshua",
    "sourceInvestment": "Coronation Global Emerging Markets Flexible (P)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202450595137",
    "identityNo": "0406055186083",
    "portfolioName": "Wilmans, Joshua",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed FOF (A)",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Wilmans, Joshua",
    "sourceInvestment": "Wealthworks Prime Managed FOF (A)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202450595137",
    "identityNo": "0406055186083",
    "portfolioName": "Wilmans, Joshua",
    "platform": "Prime",
    "investmentName": "Centaur Bci Flexible Fund (C)",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.5,
    "sourceClient": "Wilmans, Joshua",
    "sourceInvestment": "Centaur Bci Flexible Fund (C)",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202204040005",
    "identityNo": "1904295838082",
    "portfolioName": "Worrall, Charlie Christopher",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Worrall, Charlie Christopher",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  },
  {
    "accountCode": "PRI202204040006",
    "identityNo": "1709010893084",
    "portfolioName": "Worrall, Isla Elizabeth",
    "platform": "Prime",
    "investmentName": "Wealthworks Prime Managed Fund of Funds",
    "rebateAnnualPercent": 0.4,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Worrall, Isla Elizabeth",
    "sourceInvestment": "Wealthworks Prime Managed Fund of Funds",
    "matchScore": 200
  }
];

export const canonicalFeeFallbackMappings = [
  {
    "accountCode": "0315.4230",
    "identityNo": "6909305074086",
    "portfolioName": "Keren, Avi & Glynis",
    "platform": "Julius Baer",
    "investmentName": "*",
    "rebateAnnualPercent": 0.0,
    "advisoryAnnualPercent": 0.0,
    "sourceClient": "Keren, Avi & Glynis",
    "sourceInvestment": "Equities",
    "matchScore": 100
  }
];
